### ISSUE TITLE
where is the files go to after successful installation

### ISSUE THREAD

**Issue by kwccoin** [devkitPro/pacman#50]
It seems all go well 

```
  % sudo installer -pkg ~/Downloads/devkitpro-pacman-installer.pkg -target /
  Password:
  installer: Package name is devkitpro-pacman-installer
  installer: Installing at base path /
  installer: The install was successful.
```

I globally search but not sure where it go.

BTW another instruction said something like:

```
export DEVKITPRO=/opt/devkitpro
export DEVKITARM=${DEVKITPRO}/devkitARM
export DEVKITPPC=${DEVKITPRO}/devkitPPC
export PATH=${DEVKITPRO}/tools/bin:$PATH
```

I check the /opt and it only has homebrew and x11

Sorry for such basic question and hope got some answer before I move onto my next steps to tailor made for work under vs code (which might be an issue as not sure I got any sample of the json etc.)
